202 fix flaky tests
DiamondLightSource/dodal pull request #219
Opened 2023-10-26 16:07 UTC by dperl-dls

Fixes #202 

### Instructions to reviewer on how to test:
1. Run `while python -m pytest --random-order -m "not s03" ; do :; done` and confirm that tests do not fail for many runs - but ignore segfault at the end of tests as long as no tests failed

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)

2023-10-26 17:10 UTC, DominicOram commented on src/dodal/devices/utils.py
> +        LOGGER.info(f"Status closing_func got {old_status}")
Should: This was just for testing, we should remove now

2023-10-26 17:10 UTC, DominicOram commented on src/dodal/devices/utils.py
> +        LOGGER.info(f"Status of run func {status}")
Should: As above, remove now

2023-10-26 17:12 UTC, DominicOram commented on tests/devices/unit_tests/test_utils.py
> +    dummy_func.assert_called_once
Should: You're not actually calling this?

2023-10-26 17:13 UTC, DominicOram commented on tests/devices/unit_tests/test_utils.py
> +        pass
Should: I think slightly cleaner for dummy_func to return a good status then we don't expect any exception

2023-10-26 17:14 UTC, DominicOram commented on tests/devices/unit_tests/test_utils.py
>      dummy_func.assert_called_once
Should: This needs to be called

2023-10-26 17:14 UTC, DominicOram commented on tests/devices/unit_tests/test_utils.py
> +        run_functions_without_blocking([lambda: get_good_status(), dummy_func])
Should: We should get the returned status and wait on it to make sure it's tidied

2023-10-29 17:56 UTC, DominicOram requested changes
Looks good, thanks. Can you merge main and then also https://github.com/DiamondLightSource/dodal/pull/221 to confirm all the tests are passing in CI, then happy to approve.

2023-10-31 10:56 UTC, dperl-dls commented
When I run the tests a lot of times there are still occasionally threads which don't get tidied up, but I think we should fix them separately

2023-11-07 10:01 UTC, DominicOram approved these changes
Great, thank you!

2023-11-07 10:01 UTC, merged