Artemis554
DiamondLightSource/dodal pull request #25
Opened 2023-03-16 09:25 UTC by dperl-dls

Goes with changes in

2023-03-16 15:28 UTC, DominicOram commented
Can you make the PR title a bit more descriptive, dodal will use it for release note generation so should probably use something that makes sense to general DLS devs

2023-03-27 14:34 UTC, DominicOram approved these changes
Changes here look mostly good. Most comments are on Artemis PR. Do we still want the component in the OAV to be called snapshot, after renaming it to `MJPG`?

2023-03-27 14:34 UTC, DominicOram commented on src/dodal/devices/areadetector/plugins/MXSC.py
> +    blocking_callbacks_pv: EpicsSignal = Component(EpicsSignal, "BlockingCallbacks")
Could: I think the word PV is a bit redundant here. We know they're all PVs

2023-05-11 16:06 UTC, DominicOram requested changes
Thanks, mostly looks good, couple of questions in code

2023-05-12 08:12 UTC, dperl-dls commented on .github/workflows/code.yml
> -        python: ["3.9", "3.10", "3.11"]
3.9 is still there, in the next bit which tests non-editable installation, I just kept the same format as before :)

2023-05-12 08:44 UTC, DominicOram commented on .github/workflows/code.yml
> -        python: ["3.9", "3.10", "3.11"]
Yes, I see, apologies

2023-05-12 09:37 UTC, DominicOram approved these changes
Great, thank you!

2023-05-12 09:44 UTC, merged