Aravis Detector: Warmup HDF Writer During Stage
DiamondLightSource/dodal pull request #34
Opened 2023-04-04 11:02 UTC by callumforrester

Changes:
* Make ADAravis detector pass a frame through the HDF5 writer on staging to ensure that the ROIs are synced
* Make this frame as short as possible for maximum efficiency

2023-04-04 12:00 UTC, DominicOram requested changes
Minor changes/questions. Also, are we able to have a couple of unit tests on this?

2023-04-04 13:02 UTC, callumforrester commented on src/dodal/devices/areadetector/adaravis.py
> +        self.cam.acquire.put_complete = True
Yes, I think it should actually go in `__init__` because it's sensible to have as default behaviour for this detector

2023-04-04 13:04 UTC, callumforrester commented on src/dodal/devices/areadetector/adaravis.py
> +            signal.set(value).wait(timeout=10)
Not sure, I based on it a similar function in the hdf5 plugin (not compatible with the aravis driver), which doesn't use finally. I think the logic is that if something goes wrong here, we shouldn't do any cleanup and leave the debris strewn everywhere for easy investigation.

2023-04-04 13:16 UTC, callumforrester commented
@DominicOram 
On unit tests: I would very much like to write some, unsure what the best strategy is though. The logic is fairly tightly coupled to I/O and the behaviour of an AreaDetector driver. Not sure what the nicest way to test it is. Any insight you have would be great.

2023-04-04 13:38 UTC, DominicOram commented on src/dodal/devices/areadetector/adaravis.py
> +            signal.set(value).wait(timeout=10)
I guess that's fair enough. I have no strong opinion w/o knowing the use case in depth but just highlighting it as a potential gotcha

2023-04-04 16:15 UTC, DominicOram commented
> @DominicOram On unit tests: I would very much like to write some, unsure what the best strategy is though. The logic is fairly tightly coupled to I/O and the behaviour of an AreaDetector driver. Not sure what the nicest way to test it is. Any insight you have would be great.

You're right testing this stuff is a pain, I think it's a limitation in `ophyd`. Ideally we would be able to do something like:
```python
from unittest.mock import MagicMock

from ophyd.sim import make_fake_device

from dodal.devices.areadetector.adaravis import AdAravisDetector


def test_priming_returns_settings_to_previous():
    det = make_fake_device(AdAravisDetector)(name="")
    det.hdf.enable.sim_put(0)
    det.stage()
    assert det.enable.get() == 0


def test_priming_triggers():
    det = make_fake_device(AdAravisDetector)(name="")
    det.cam.aquire = MagicMock()
    det.stage()
    assert det.cam.aquire.set.has_calls == [0, 1]
```
But the `make_fake_device` mixed with `set().wait()` and the inability to set mocks like `det.cam = MagicMock()` really doesn't like you doing this. Let's leave for now, hopefully better in v2, @coretl?

2023-04-04 16:33 UTC, DominicOram approved these changes

2023-04-05 07:27 UTC, merged

2023-04-05 07:51 UTC, coretl commented
> But the `make_fake_device` mixed with `set().wait()` and the inability to set mocks like `det.cam = MagicMock()` really doesn't like you doing this. Let's leave for now, hopefully better in v2, @coretl?

We should be able to do something like this in v2:

```python
from ophyd.v2.core import set_sim_value

async def test_priming_returns_settings_to_previous():
    det = AdAravisDetector(name="")
    await det.connect(sim=True)
    set_sim_value(det.hdf.enable, 0)
    det.stage()
    assert det.enable.get() == 0
```

There is also `set_sim_put_proceeds` to allow you to make a sim signal block on put with wait=True so you can simulate a long running caput callback