Convert Zebra device to ophyd async
DiamondLightSource/dodal pull request #382
Opened 2024-03-14 17:15 UTC by noemifrisina

Fixes #356

### Instructions to reviewer on how to test:
1. Tests pass
2. 

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)

2024-03-18 16:50 UTC, noemifrisina commented on src/dodal/devices/zebra.py
> +        self.armed = epics_signal_rw(ArmDemand, prefix + "PC_ARM_OUT")
Thanks, I didn't know that and the unit tests do not fail whatever the enum signal passed (opening an issue on that).

I've now turned the relevant enums in here to (str, Enum). 
Tbh, I don't really like using a boolean in this case - the arming device- , I find it clearer to have a way to ask for arm/disarm. I fixed the type of that particular signal but left the demand to be passed to the set method as `ArmDemand`.

2024-03-26 16:46 UTC, DominicOram requested changes
Thanks, one comment, otherwise I think it's good!

2024-03-26 16:46 UTC, DominicOram commented on src/dodal/devices/zebra.py
> +        await self.armed.set(demand.value)
Should: I think `armed` is a read-only signal from EPICS as to whether the zebra thinks it's armed. We can't set it. Instead I think we want to observe it after we've done the set and wait for it to be as we expect. See other places we use `observe_value`

2024-03-28 16:24 UTC, olliesilvester approved these changes
David's change looks good to me

2024-04-02 09:20 UTC, merged