Add NeXus friendly fields to DCM
DiamondLightSource/dodal pull request #541
Opened 2024-05-15 12:44 UTC by callumforrester

Fixes #397 

### Instructions to reviewer on how to test:
1. Confirm tests pass

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly

2024-05-24 08:07 UTC, DiamondJoseph requested changes
Bad News: NXinsertion_device can take arbitrarily many crystals, and a DualCrystalMonochromator has two crystals.

The i22 requirement has

crystal_1 = DCMCrystal(
    usage="Bragg",
    type="Silicon",
    reflection=(1, 1, 1),
    d_spacing=3.13475,
)

crystal_2 = DCMCrystal(
    usage="Bragg",
    type="Silicon",
    reflection=(1, 1, 1),
    d_spacing=3.13475,
)

I think it'll need to take a dict...

2024-05-24 08:07 UTC, DiamondJoseph commented on src/dodal/beamlines/i22.py
> +) -> FocusingMirror:
```suggestion
) -> DCM:
```

2024-05-24 08:14 UTC, callumforrester commented on src/dodal/devices/dcm.py
> +        crystal: DCMCrystal | None = None,
Hmm, do we need to wait for this then?

https://github.com/bluesky/ophyd-async/issues/311

2024-05-24 08:14 UTC, callumforrester commented on src/dodal/devices/dcm.py
> +class DCMCrystal:
```suggestion
class MonochromatorCrystal:
```

2024-05-24 08:15 UTC, callumforrester commented
Currently fails the system test for i22, PV prefix may be wrong

2024-06-03 13:58 UTC, callumforrester commented
Update on this issue: I think for now we need to make another DCM class and an issue to reconcile. 
Supporting multiple crystals is also still TODO

2024-06-05 19:12 UTC, callumforrester commented
Closing for now in favour of #598

2024-06-05 19:12 UTC, closed without merging