PMAC device to ophyd_async
DiamondLightSource/dodal pull request #561
Opened 2024-05-21 09:58 UTC by noemifrisina

Needed for [Mx#98](https://github.com/DiamondLightSource/mx_bluesky/issues/98)

Convert PMAC device to ophyd_async and add functionality to set various PMAC_strings.

### Instructions to reviewer on how to test:
1. Tests pass

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://github.com/DiamondLightSource/dodal/wiki/Device-Standards)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly

2024-06-10 08:55 UTC, DominicOram requested changes
Great, thank you. Some comments in code

2024-06-10 08:55 UTC, DominicOram commented on src/dodal/devices/i24/pmac.py
> +    LASER2OFF = " M812=0 M811=1"
Nit: I think some `_` would make these more readable:
```suggestion
    LASER_1_ON = " M712=1 M711=1"
    LASER_1_OFF = " M712=0 M711=1"
    LASER_2_ON = " M812=1 M811=1"
    LASER_2_OFF = " M812=0 M811=1"
```

2024-06-10 08:55 UTC, DominicOram commented on src/dodal/devices/i24/pmac.py
> +class PMACStringMove(Triggerable):
Could: A docstring on this would be nice

2024-06-17 15:21 UTC, dperl-dls approved these changes
lgtm, thanks

2024-06-18 08:59 UTC, merged