Update example create-beamline docs for new preferred method
DiamondLightSource/dodal pull request #917
Opened 2024-11-26 09:44 UTC by DiamondJoseph

Update docs for new device_factory decorator

### Instructions to reviewer on how to test:
1. Read docs
2. Ensure that docs make sense

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://diamondlightsource.github.io/dodal/main/reference/device-standards.html)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly
- [ ] Have the connection tests for the relevant beamline(s) been run via `dodal connect ${BEAMLINE}`

2025-02-19 09:39 UTC, DominicOram requested changes
Thanks, couple of comments.

2025-02-19 09:39 UTC, DominicOram commented on docs/how-to/create-beamline.rst
> -        return AdAravisDetector(name=name, prefix=f"{BL}-DI-DCAM-01:")
Should: Now that you've removed the detector the text above about having a synchrotron and a detector doesn't make sense. If we don't want to use the `AdAravisDetector` as an example we should have some example of a device instantiated w/o `skip_device`

2025-02-19 09:39 UTC, DominicOram commented on docs/how-to/create-beamline.rst
> +        return Synchrotron()
Should: Why do we want this in the docs? Presumably we would like to encourage people to always be using `@device_factory`?

2025-02-19 09:39 UTC, DominicOram commented on docs/how-to/create-beamline.rst
>      @skip_device(lambda: BL == "s41")  # Conditionally do not instantiate this device
Should: This is the old way of doing things. I think it's fine that the behavior is still there whilst we're depreciating it but we shouldn't be documenting it in a how to otherwise people might use it for new stuff

2025-02-19 09:39 UTC, DominicOram commented on docs/how-to/create-beamline.rst
> +        - a maximum of once
Should: At a first glance this implies you should only call `synchrotron()` once, not that it's cached

2025-03-06 15:21 UTC, DiamondJoseph commented on docs/how-to/create-beamline.rst
> -        return AdAravisDetector(name=name, prefix=f"{BL}-DI-DCAM-01:")
I've restored the Detector. I had originally thought of showing the pros and cons of all of the methods currently available, and using the Synchrotron for all of them to make it clear what was going on, but I think you're right and we don't need to highlight the outdated ways of doing things.

2025-03-06 15:22 UTC, DiamondJoseph commented on docs/how-to/create-beamline.rst
> +        - a maximum of once
How's the new wording, other than wordier?

2025-03-06 16:02 UTC, DominicOram approved these changes
Great, thank you!

2025-03-06 16:02 UTC, merged