Update p38 to use device_factory
DiamondLightSource/dodal pull request #921
Opened 2024-11-26 12:29 UTC by DiamondJoseph

Updates p38 beamline definition to use device_factory

### Instructions to reviewer on how to test:
1. Check p38 beamline can still connect with dodal connect test

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://diamondlightsource.github.io/dodal/main/reference/device-standards.html)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly
- [ ] Have the connection tests for the relevant beamline(s) been run via `dodal connect ${BEAMLINE}`

2024-11-26 13:22 UTC, stan-dot approved these changes
better than main even if does not connect

2024-11-26 16:17 UTC, stan-dot commented
> ppump
idk where it is tbh

2024-11-27 12:37 UTC, stan-dot commented
I presume that the mock logic is not working for the slits

2024-12-11 13:32 UTC, callumforrester requested changes
@DiamondJoseph and @stan-dot can you recommend a machine to run the system tests from? I need a RHEL8 one that can access the P38 PVs

2024-12-11 13:32 UTC, callumforrester commented on src/dodal/devices/pressure_jump_cell.py
Not sure I understand the reasons for any of the changes in this file?

2024-12-11 15:34 UTC, stan-dot commented on src/dodal/devices/pressure_jump_cell.py
the strictenum was failing I think and the voltage is maybe fixable at epics layer . I spoke with @barnettwilliam about this two weeks ago

2024-12-11 15:34 UTC, stan-dot commented on src/dodal/devices/pressure_jump_cell.py
please run the tests from RHEL 8.10 machine p38-ws003

2024-12-11 16:50 UTC, callumforrester commented on src/dodal/devices/pressure_jump_cell.py
Okay, if the voltage is a thing to be fixed I'd prefer it as a Github issue rather than a comment

2024-12-11 16:52 UTC, callumforrester requested changes
System tests are currently failing for me

```
+ dodal connect p38
Attempting connection to p38 (using dodal.beamlines.p38)
ERROR:root:device `open` raised unexpected exception TypeError
Traceback (most recent call last):
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_device.py", line 187, in connect
    await self._connect_task
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_signal.py", line 67, in connect_real
    await self.backend.connect(timeout)
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 264, in connect
    self.converter = make_converter(self.datatype, self.initial_values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 211, in make_converter
    raise TypeError(
TypeError: BL38P-EA-HPXC-01:V5:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
ERROR:root:device `open` raised unexpected exception TypeError
Traceback (most recent call last):
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_device.py", line 187, in connect
    await self._connect_task
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_signal.py", line 67, in connect_real
    await self.backend.connect(timeout)
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 264, in connect
    self.converter = make_converter(self.datatype, self.initial_values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 211, in make_converter
    raise TypeError(
TypeError: BL38P-EA-HPXC-01:V6:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
ERROR:root:device `open` raised unexpected exception TypeError
Traceback (most recent call last):
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_device.py", line 187, in connect
    await self._connect_task
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_signal.py", line 67, in connect_real
    await self.backend.connect(timeout)
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 264, in connect
    self.converter = make_converter(self.datatype, self.initial_values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 211, in make_converter
    raise TypeError(
TypeError: BL38P-EA-HPXC-01:V1:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
ERROR:root:device `open` raised unexpected exception TypeError
Traceback (most recent call last):
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_device.py", line 187, in connect
    await self._connect_task
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_signal.py", line 67, in connect_real
    await self.backend.connect(timeout)
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 264, in connect
    self.converter = make_converter(self.datatype, self.initial_values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/epics/core/_aioca.py", line 211, in make_converter
    raise TypeError(
TypeError: BL38P-EA-HPXC-01:V3:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
ERROR:bluesky:Run aborted
Traceback (most recent call last):
  File "/dodal/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1605, in _run
    msg = self._plan_stack[-1].send(resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/plan_stubs/_ensure_connected.py", line 33, in ensure_connected
    raise connect_task.exception()
  File "/dodal/venv/lib/python3.11/site-packages/ophyd_async/core/_utils.py", line 161, in wait_for_connection
    raise NotConnected.with_other_exceptions_logged(exceptions)
ophyd_async.core._utils.NotConnected: 
high_pressure_xray_cell: NotConnected:
    all_valves_control: NotConnected:
        fast_valve_control: NotConnected:
            5: NotConnected:
                open: TypeError: BL38P-EA-HPXC-01:V5:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
            6: NotConnected:
                open: TypeError: BL38P-EA-HPXC-01:V6:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
        valve_control: NotConnected:
            1: NotConnected:
                open: TypeError: BL38P-EA-HPXC-01:V1:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
            3: NotConnected:
                open: TypeError: BL38P-EA-HPXC-01:V3:OPENSEQ with inferred datatype int cannot be coerced to ValveOpenSeqRequest
    pressure_transducers: NotConnected:
        3: NotConnected:
            slow_beckhoff_voltage_readout: NotConnected: ca://BL38P-EA-ADC-03:CH1
undulator: NotConnected:
    gap_motor: NotConnected:
        motor_egu: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.EGU
        velocity: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.VELO
        user_readback: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.RBV
        user_setpoint: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.VAL
        max_velocity: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.VMAX
        acceleration_time: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.ACCL
        precision: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.PREC
        deadband: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.RDBD
        motor_done_move: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.DMOV
        low_limit_travel: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.LLM
        high_limit_travel: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.HLM
        motor_stop: NotConnected: ca://SR38P-MO-SERVC-01:BLGAPMTR.STOP
    current_gap: NotConnected: ca://SR38P-MO-SERVC-01:CURRGAPD
    gap_access: NotConnected: ca://SR38P-MO-SERVC-01:IDBLENA
dcm: NotConnected:
    bragg: NotConnected:
        motor_egu: NotConnected: ca://BRAGG.EGU
        velocity: NotConnected: ca://BRAGG.VELO
        user_readback: NotConnected: ca://BRAGG.RBV
        user_setpoint: NotConnected: ca://BRAGG.VAL
        max_velocity: NotConnected: ca://BRAGG.VMAX
        acceleration_time: NotConnected: ca://BRAGG.ACCL
        precision: NotConnected: ca://BRAGG.PREC
        deadband: NotConnected: ca://BRAGG.RDBD
        motor_done_move: NotConnected: ca://BRAGG.DMOV
        low_limit_travel: NotConnected: ca://BRAGG.LLM
        high_limit_travel: NotConnected: ca://BRAGG.HLM
        motor_stop: NotConnected: ca://BRAGG.STOP
    offset: NotConnected:
        motor_egu: NotConnected: ca://OFFSET.EGU
        velocity: NotConnected: ca://OFFSET.VELO
        user_readback: NotConnected: ca://OFFSET.RBV
        user_setpoint: NotConnected: ca://OFFSET.VAL
        max_velocity: NotConnected: ca://OFFSET.VMAX
        acceleration_time: NotConnected: ca://OFFSET.ACCL
        precision: NotConnected: ca://OFFSET.PREC
        deadband: NotConnected: ca://OFFSET.RDBD
        motor_done_move: NotConnected: ca://OFFSET.DMOV
        low_limit_travel: NotConnected: ca://OFFSET.LLM
        high_limit_travel: NotConnected: ca://OFFSET.HLM
        motor_stop: NotConnected: ca://OFFSET.STOP
    perp: NotConnected:
        motor_egu: NotConnected: ca://PERP.EGU
        velocity: NotConnected: ca://PERP.VELO
        user_readback: NotConnected: ca://PERP.RBV
        user_setpoint: NotConnected: ca://PERP.VAL
        max_velocity: NotConnected: ca://PERP.VMAX
        acceleration_time: NotConnected: ca://PERP.ACCL
        precision: NotConnected: ca://PERP.PREC
        deadband: NotConnected: ca://PERP.RDBD
        motor_done_move: NotConnected: ca://PERP.DMOV
        low_limit_travel: NotConnecte [...]

2024-12-11 17:29 UTC, stan-dot commented
@callumforrester please include such long logs as a file not as a comment string

2024-12-13 13:35 UTC, callumforrester commented
@stan-dot my bad, edited

2025-01-13 15:17 UTC, callumforrester commented
System tests continuing to fail: 
[dodal-connect-p38-log.txt](https://github.com/user-attachments/files/18398589/dodal-connect-p38-log.txt)

2025-01-16 09:48 UTC, stan-dot commented
I am not sure how to track what is the actual status of the p38 beamline. maybe some things don't connect because they are physically disconnected

that was the case for i20-1

2025-01-17 13:22 UTC, stan-dot commented
discussed the connection issues with @barnettwilliam , some pressure jump device issues waiting for #812  (?)

2025-01-20 16:50 UTC, stan-dot commented
and slits_N where N is from 1 to 6 also are not connected

caget times out:
`caget BL38P-MO-FSWT-01:FILTER-101:STATUS_RBV`

2025-01-24 12:24 UTC, stan-dot commented on src/dodal/devices/pressure_jump_cell.py
out of date, the tests are failing still

2025-01-27 16:45 UTC, stan-dot commented
@DiamondJoseph have there been any issues with the mock not working with `device_factory`? that's what I suspect is happening

2025-01-27 16:53 UTC, DiamondJoseph commented
> @DiamondJoseph have there been any issues with the mock not working with `device_factory`? that's what I suspect is happening

That does appear to be the case. I know blueapi respects mock=True, but I thought the dodal connect tests did too. Leave it to me, I'll look at it tomorrow.

2025-01-27 17:11 UTC, stan-dot commented
> but I thought the dodal connect tests did too

fantastic... this was one of the edge cases that  I got stuck at when doing device_factory back in October before you did your implementation


I was trying to make it work there too, and now we're witnessing a miss


this is an issue for all the 'update-ixx' PRs

2025-02-03 11:26 UTC, stan-dot commented
this is the relevant issue

https://github.com/DiamondLightSource/dodal/issues/925

2025-02-04 09:00 UTC, barnettwilliam approved these changes

2025-02-11 10:40 UTC, stan-dot commented
@barnettwilliam after the latest merge we've got a branch conflict, could you please take a look?

2025-02-13 08:11 UTC, barnettwilliam commented
Yes will do

2025-02-13 09:39 UTC, barnettwilliam commented
@stan-dot conflicts are now resolved

2025-02-19 07:49 UTC, barnettwilliam commented
@DominicOram please could you review this in lieu of Callum

2025-02-19 09:30 UTC, DominicOram approved these changes
Thanks. As discussed above there's still lots of failures but I agree it's no worse than before

2025-02-19 09:30 UTC, merged