949 make ophyd devices for the diagonstics for i10
DiamondLightSource/dodal pull request #960
Opened 2024-12-13 14:34 UTC by Relm-Arrowny

Fixes #ISSUE

### Instructions to reviewer on how to test:
1. Do thing x
2. Confirm thing y happens

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://diamondlightsource.github.io/dodal/main/reference/device-standards.html)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly
- [ ] Have the connection tests for the relevant beamline(s) been run via `dodal connect ${BEAMLINE}`

2025-01-13 15:14 UTC, callumforrester commented on src/dodal/devices/i10/diagnostics.py
> +    an older/different model"""
I would like @coretl's opinion on this approach, whether we should make a configurable "super detector" in ophyd-async or accept variations like these

2025-01-13 18:53 UTC, coretl commented on src/dodal/devices/i10/diagnostics.py
> +    an older/different model"""
This should be rolled into ophyd-async AravisDetector. Since https://github.com/bluesky/ophyd-async/pull/606 this should now be possible. We pass `stats` as a plugin to the init. I'm unsure why the datatype change was needed.

2025-01-24 12:54 UTC, DominicOram requested changes
Great, thanks! I've added a bunch of suggestions based on how I would do a similar device in MX but obviously I don't know your usecase so feel free to reject suggestions if they don't work for you. Do you have some example plans that use the devices? I was expecting to see some in https://github.com/DiamondLightSource/i10-bluesky but couldn't, maybe I'm just missing them.

2025-01-24 12:54 UTC, DominicOram commented on src/dodal/devices/i10/diagnostics.py
> +        await self.drv.acquire.set(True)
Should: I think you could just inherit from `SingleTriggerDetector` then? Something like:
```suggestion
class I10CentroidDetector(SingleTriggerDetector):
    """Detector to read out the centroid position,
    this is based off the SingleTriggerDetector in ophyd_async with added
    readable defaults"""

    def __init__(
        self,
        prefix: str,
        name: str = "",
    ) -> None:
        driver = I10AravisDriverIO(prefix=prefix)
        super().__init__(driver, [driver.centroid_x, driver.centroid_y], name)
```

2025-01-24 12:54 UTC, DominicOram commented on src/dodal/devices/i10/diagnostics.py
> +            )
Should: As above with `drop_down` -> `position`

2025-01-24 12:54 UTC, DominicOram commented on src/dodal/devices/i10/diagnostics.py
> +        stage_write_suffix: str = "CON",
Should: I can't see anywhere in the code currently where we use different values for `stage_write_enum`, `stage_read_enum`, `stage_read_suffix` or `stage_write_suffix` than the defaults. I would just hardcode them in below until you have a case where they are different as it leads to lots of boilerplate

2025-01-24 12:54 UTC, DominicOram commented on tests/devices/i10/test_diagnostics.py
> +async def test_I10CentroidDetector_with_blueSky(
Nit: My preference is to name tests very verbosely and explicitly so it's clear what you're testing. For example here I would name it something like `test_when_I10CentroidDetector_is_counted_in_plan_then_emitted_document_contains_expected_values`. If you have vague names I think it leads to the temptation to make one big test that tests loads of different stuff, that test then becomes long to run and hard to debug

2025-01-24 14:01 UTC, Relm-Arrowny commented on src/dodal/devices/i10/slits.py
> +class BladeDrainCurrents(Device):
Just a very quick one, I will add the dostring later, The way we use drain current on mirror the absolute flux does not matter we use it to normalise the detector so it is always relative and it has the added advantage of you do not put anything in the beam path that is not needed.  As for the slits/blade drain, we use it to correct correct the beam position(feedback). E.g. depending of the drain current values on the left and right blades we will move the mirror pitch to make sure it always in the right place.     
I am not sure I would call it a technique, it is mostly  [photoelectric effect](https://www.nobelprize.org/prizes/physics/1921/summary/). In theory you can convert them into flux but there are a lot assumptions/corrections you have to make, for example the beam distribution, as we are not intercepting all of the beam, furthermore drain current also suffer form charging up and has a strong energy dependence, it will be a very big job to do all the corrections.

2025-01-24 14:08 UTC, Relm-Arrowny commented on src/dodal/devices/i10/diagnostics.py
> +    """Diagnotic 5a detection with drain current and photo diode"""
I do but every time I rebuild container, I lost it and forgot to reinstall. :(

2025-01-28 09:29 UTC, coretl commented on src/dodal/devices/i10/diagnostics.py
> +    """Diagnotic 5a detection with drain current and photo diode"""
You can put them in `.config/Code/User/settings.json` to make them always installed in a dev container:
https://code.visualstudio.com/docs/devcontainers/containers#_always-installed-extensions

2025-02-19 15:44 UTC, Relm-Arrowny commented on src/dodal/devices/i10/slits.py
> +class I10SlitsBlades(Slits):
I guess I do not definitely need it to be able to, it is an old habit of mine when I align slit, I like to scan one blade at a time, where I completely block the beam with just 1 blade and define the half cut position of as 0 so that 0,0,0,0 for the blade is the close/centre position, but I have not done that for a very long time.
The other time I would use it is for clean up slits where I would like to block more on one side. But the same effect can be achieve by closing the gap and moving the centre at the same time, which is slightly painful.

2025-02-19 15:52 UTC, Relm-Arrowny commented on src/dodal/devices/i10/diagnostics.py
> +    an older/different model"""
The issue for datatype is without changing it I with get the follow error as datatype is strict enum `       drv: NotConnected:
                data_type: TypeError: BL10I-DI-PHDGN-01:DCAM:CAM:DataType_RBV has choices ('UInt8', 'UInt16'), but <enum 'ADBaseDataType'> requested ['Int8', 'UInt8', 'Int16', 'UInt16', 'Int32', 'UInt32', 'Int64', 'UInt64', 'Float32', 'Float64'] to be strictly equal to them.`

2025-03-12 15:43 UTC, DominicOram requested changes
Thanks! Sorry it's taken me so long to get back round to this. Mostly comments that I think you missed from last review plus the `connect` now doesn't work

2025-03-12 15:43 UTC, DominicOram commented on src/dodal/devices/i10/slits.py
> +class BladeDrainCurrents(Device):
Thank you, that is clearer

2025-04-15 14:19 UTC, DominicOram approved these changes
Great, thank you! I think we can make the positioner more generic but I can do this in https://github.com/DiamondLightSource/dodal/issues/1176

2025-04-15 14:22 UTC, merged